# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  gen:
    dao:
      - link: "mssql:sa:Yzj123!!@tcp(172.20.17.8:1433)/CMS?encrypt=disable"
#        tables: "T_SysParameter,T_AlarmNotification,T_UserDept"
        tables: "  "
        descriptionTag: true
        noModelComment: true
        removePrefix: "T_"
        projectName: "CMS"
        outPath: "C:/Users/Iot/Desktop/Files/"

  # 打包脚本
  build:
    name: "code_gen_util"
    arch: "amd64"
    system: "windows"
    mod: "none"
    packSrc: "resource,manifest"
    version: "v1.0.0"
    output: "./bin"
    extra: ""