
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  gen:
    dao:
      - link: "mssql:sa:Yzj123!!@tcp(172.20.17.91:1433)/YangtzeFlow?encrypt=disable"
        tables: "t_file,t_flow"
        descriptionTag: true
        noModelComment: true
        removePrefix: "t_"