// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go_gen_code/internal/dao/internal"
)

// internalDocumentDao is internal type for wrapping internal DAO implements.
type internalDocumentDao = *internal.DocumentDao

// documentDao is the data access object for table document.
// You can define custom methods on it to extend its functionality as you wish.
type documentDao struct {
	internalDocumentDao
}

var (
	// Document is globally public accessible object for table document operations.
	Document = documentDao{
		internal.NewDocumentDao(),
	}
)

// Fill with you ideas below.
