// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/Jiaru0314/go_gen_code/internal/dao/internal"
)

// internalOperaLogDao is internal type for wrapping internal DAO implements.
type internalOperaLogDao = *internal.OperaLogDao

// operaLogDao is the data access object for table sys_opera_log.
// You can define custom methods on it to extend its functionality as you wish.
type operaLogDao struct {
	internalOperaLogDao
}

var (
	// OperaLog is globally public accessible object for table sys_opera_log operations.
	OperaLog = operaLogDao{
		internal.NewOperaLogDao(),
	}
)

// Fill with you ideas below.
